In [3]:
import cv2 as cv
import numpy as np

In [5]:
classifier = cv.CascadeClassifier("haarcascade_frontalface_default.xml") # for front face
#classifier2 = cv.CascadeClassifier("haarcascade_profileface.xml")   # for side face
cam = cv.VideoCapture(0)

while True:
    _, img = cam.read()
    img = cv.flip(img, 1)
    front_faces = classifier.detectMultiScale(img, 1.4, 5)
    #side_faces = classifier2.detectMultiScale(img, 1.4, 5)
    #print (front_faces, side_faces)
    print(front_faces)
    for (x,y,w,h) in front_faces :
        cv.rectangle(img, (x,y), (x+w, y+h), (255,255,255), 5)
        front_face = img[y:y+h, x:x+w, :]
        cv.imshow("front face", front_face)
        front_face = cv.blur(front_face, (16,16))
        img[y:y+h, x:x+w, :] = front_face

    # for (x_, y_, w_, h_) in side_faces:
    #     cv.rectangle(img, (x,y), (x+w, y+h), (0, 0, 0), 5)
    #     side_face = img[y_:y_+h_, x_:x_+w_, :]
    #     cv.imshow("side face", side_face)
    
    
    cv.imshow("Camera View", img)
    
    

    if cv.waitKey(1) == 27 :
        cam.release()
        cv.destroyAllWindows()
        break


()
[[285 268 181 181]]
[[287 268 181 181]]
[[286 266 181 181]]
[[285 267 181 181]]
[[284 265 181 181]]
[[283 264 181 181]]
[[283 265 181 181]]
[[282 266 181 181]]
[[282 266 181 181]]
[[282 268 181 181]]
[[278 269 181 181]]
[[279 270 181 181]]
[[279 270 181 181]]
[[279 270 181 181]]
[[278 269 181 181]]
[[276 268 181 181]]
[[278 269 181 181]]
[[275 269 181 181]]
[[275 270 181 181]]
[[275 270 181 181]]
[[275 266 181 181]]
[[274 263 181 181]]
[[274 265 181 181]]
[[273 264 181 181]]
[[273 264 181 181]]
[[272 261 181 181]]
[[272 261 181 181]]
[[269 262 181 181]]
[[266 265 181 181]]
[[261 261 181 181]]
[[260 258 181 181]]
[[256 260 181 181]]
[[256 256 181 181]]
[[257 261 181 181]]
[[257 261 181 181]]
[[257 261 181 181]]
[[258 259 181 181]]
[[254 256 181 181]]
[[253 257 181 181]]
[[252 257 181 181]]
[[252 260 181 181]]
[[251 259 181 181]]
[[251 259 181 181]]
[[249 259 181 181]]
[[252 259 181 181]]
()
[[249 255 181 181]]
[[253 257 181 181]]
[[253 257 181 181]]
[[255 263 181 181]]
[[257 262 181 

In [47]:
front_faces = [
    [[175, 149, 253, 253]], 
    [[174, 148, 253, 253]], 
    [[172, 148, 253, 253]], 
    [[172, 148, 253, 253], [214, 181, 181, 181]],
    [[178, 148, 253, 253], [215, 180, 181, 181]],
    [[172, 148, 253, 253], [214, 178, 181, 181]],
    [[178, 150, 253, 253], [217, 180, 181, 181]],
    [[176, 148, 253, 253], [217, 181, 181, 181]],
    [[175, 149, 253, 253], [218, 181, 181, 181]]
]

for faces in front_faces:
    if(len(faces)>1):
        for f in faces:
            print(f, "\n")


[172, 148, 253, 253] 

[214, 181, 181, 181] 

[178, 148, 253, 253] 

[215, 180, 181, 181] 

[172, 148, 253, 253] 

[214, 178, 181, 181] 

[178, 150, 253, 253] 

[217, 180, 181, 181] 

[176, 148, 253, 253] 

[217, 181, 181, 181] 

[175, 149, 253, 253] 

[218, 181, 181, 181] 

