In [1]:
import cv2 as cv
import numpy as np


In [7]:
classifier = cv.CascadeClassifier("haarcascade_frontalface_default.xml")
cam = cv.VideoCapture(0)
while True:
    _, img = cam.read()
    img = cv.flip(img, 1)
    faces = classifier.detectMultiScale(img, 1.1, 8)
    
    print(faces)
    print("---------------------------")

    for (x, y, w, h) in faces :
        cv.rectangle(img, (x,y), (x+w, y+h) , (255,255,255), 5)
    cv.imshow("Frame ", img)
    if cv.waitKey(1) ==27:
        cam.release()
        cv.destroyAllWindows()
        break

[[244 232 177 177]]
---------------------------
[[243 230 181 181]]
---------------------------
[[244 230 179 179]]
---------------------------
[[245 231 176 176]]
---------------------------
[[243 230 179 179]]
---------------------------
[[245 232 175 175]]
---------------------------
[[245 230 178 178]]
---------------------------
[[244 230 178 178]]
---------------------------
[[246 231 177 177]]
---------------------------
[[244 229 181 181]]
---------------------------
[[246 230 179 179]]
---------------------------
[[251 230 176 176]]
---------------------------
[[253 230 175 175]]
---------------------------
[[255 228 177 177]]
---------------------------
[[260 228 176 176]]
---------------------------
[[260 226 176 176]]
---------------------------
[[261 227 174 174]]
---------------------------
[[258 225 179 179]]
---------------------------
[[258 225 172 172]]
---------------------------
[[258 214 172 172]]
---------------------------
[[259 213 168 168]]
--------------------

In [5]:
classifier = cv.CascadeClassifier("haarcascade_frontalface_default.xml")
cam = cv.VideoCapture(0)
while True:
    _, img = cam.read()
    img = cv.flip(img, 1)
    faces = classifier.detectMultiScale(img, 2, 5)
 
    for (x, y, w, h) in faces :
        cv.rectangle(img, (x,y), (x+w, y+h) , (255,255,255), 5)
        
    cv.imshow("Frame ", img)
    
    if cv.waitKey(1) ==27:
        cam.release()
        cv.destroyAllWindows()
        break